### ISSUE TITLE
feat: allow root.. syntax

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram/gtag#2]
We can make gtag yet a little more convenient by allowing the special keyword `root` to appear in ranges. With commit hashes changing so rapidly while working on our exercise material it can become tedious to look up the SHA of the first commit. So instead of writing something like `gtag  a13b718.. foo-##i` to address the entire range of commits one could just write `gtag  root.. foo-##i`

**Comment by 0x-r4bbit** [comment]
This is awesome

**Comment by cburgdorf** [comment]
such an swiss army knife ;)
